### ISSUE TITLE
Debian package installs into /usr/local

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mongocli#130]
I downloaded and installed the Debian package of mongocli, and it had the following files:

<pre>
carbon% dpkg -L mongocli                 
/usr
/usr/local
/usr/local/bin
/usr/local/bin/mongocli
</pre>

Per [Debian documentation](https://www.debian.org/doc/manuals/maint-guide/modify.en.html#destdir) the packaged software is supposed to use `/usr` rather than `/usr/local` namespace.

**Comment by gssbzn** [comment]
Hi @p-mongo, thanks for the feedback, we are still working on our packaging process and I think I can address this here, https://github.com/mongodb/mongocli/pull/127,
