### ISSUE TITLE
`make install` does not say what it installed and where

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mongocli#195]
I am following the [build from source](https://github.com/mongodb/mongocli#build-from-source) instructions in the readme.

First question: the steps are "prerequisites" and "fetch and install". If I am building from source, chances are I just want to build and not install anything anywhere. How does one actually perform the build step?

Second question: I ran `make install` as instructed. This produced the following output:

<pre>
carbon% make install
go install -ldflags "-X github.com/mongodb/mongocli/internal/version.Version=v1.0.0-rc2-4-gfa19b9f"
go: downloading github.com/spf13/cobra v1.0.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/spf13/viper v1.7.0
go: downloading github.com/spf13/afero v1.2.2
go: downloading go.mongodb.org/ops-manager v0.5.2-0.20200513091426-cb751656afa4
go: downloading github.com/mongodb/go-client-mongodb-atlas v0.2.1-0.20200508151240-fe2a21ab5a46
go: downloading github.com/Sectorbob/mlab-ns2 v0.0.0-20171030222938-d3aa0c295a8a
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/AlecAivazis/survey/v2 v2.0.7
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/mitchellh/mapstructure v1.3.1
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/pelletier/go-toml v1.8.0
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/google/go-querystring v1.0.0
go: downloading github.com/openlyinc/pointy v1.1.2
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: downloading golang.org/x/sys v0.0.0-20200523222454-059865788121
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/mattn/go-isatty v0.0.12
</pre>

What was installed where? Neither the output nor the instructions say.

Looking at the makefile source, it appears that `make install` installs the binary in `$GOPATH/bin/mongocli`. There is another hurdle here which is I have never defined $GOPATH. It appears that on my machine the binary got placed in `~/go/bin/mongocli`.

As a user of mongocli I would like:

- to have an ability to build mongocli without installing it.
- to know where to find the built binary.

**Comment by gssbzn** [comment]
Hi @p-mongo 
> to have an ability to build mongocli without installing it.

you can use `make build`, running just `make` will give you a list of available targets and descriptions for them

> to know where to find the built binary.

`make install` is using default go behaviour since you're installing from the source this is better explained on our [docs](https://docs.mongodb.com/mongocli/stable/install/#id7)

If you feel we can improve our project docs we welcome any contribution to our README

**Comment by p-mongo** [comment]
I made https://github.com/mongodb/mongocli/pull/201.

It would be nice if `make install` provided some output that stated where the binary was installed, but I can't find the documentation for `go install` using a web search.

**Comment by gssbzn** [comment]
@p-mongo to add an output we could probably add an `@echo` line after 
https://github.com/mongodb/mongocli/blob/fa19b9f41e6560a64551abcd5c8420bc80fe3166/Makefile#L73

we may have access to the `GOROOT` var there
