### ISSUE TITLE
atlas clusters help text misdescribes indexes

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mongocli#197]
When I run `mongocli atlas clusters` I get the following text:

<pre>
carbon% mongocli atlas clusters
The clusters command provides access to your cluster configurations. You can create, edit, and delete clusters.

Usage:
  mongocli atlas clusters [command]

Aliases:
  clusters, cluster

Available Commands:
  create      Create a MongoDB cluster.
  list        List clusters for a project.
  describe    Describe a cluster.
  delete      Delete a cluster.
  update      Update a MongoDB cluster in Atlas.
  indexes     Manage clusters for your project.

Flags:
  -h, --help   help for clusters

Global Flags:
  -P, --profile string   Profile to use from your configuration file. (default "default")

Use "mongocli atlas clusters [command] --help" for more information about a command.
</pre>

The following part seems bogus:

<pre>
  indexes     Manage clusters for your project.
</pre>

**Comment by gssbzn** [comment]
This was fixed by #140 and released on [v0.5.0](https://github.com/mongodb/mongocli/releases/tag/v0.5.0)
