### ISSUE TITLE
Usage should only be shown when usage is incorrect

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mongocli#198]
I ran `iam project list` command (following the instructions [here](https://docs.mongodb.com/mongocli/master/quick-start/#mcli-quick-start)). The command appears to have failed due to mongocli receiving an error response from atlas api. mongocli then output this api error and printed usage information:

<pre>
carbon% mongocli iam project list
Error: GET https://cloud.mongodb.com/api/atlas/v1.0/groups: 404 (request "Not Found") Atlas group 5ea35ecf445d921efae0e86b is in an invalid state and cannot be loaded.
Usage:
  mongocli iam projects list [flags]

Aliases:
  list, ls

Flags:
  -h, --help           help for list
      --orgId string   Organization ID to use. Overrides configuration file or environment variable settings.

Global Flags:
  -P, --profile string   Profile to use from your configuration file. (default "default")

2020/05/29 22:24:30 GET https://cloud.mongodb.com/api/atlas/v1.0/groups: 404 (request "Not Found") Atlas group 5ea35ecf445d921efae0e86b is in an invalid state and cannot be loaded.
</pre>

As a user of mongocli, I would like mongocli to only print usage information when 1) usage was incorrect or 2) when explicitly requested via `help`. If usage was correct and operation failed for another reason, I would like mongocli to provide relevant error information which seems like it would not be usage text.

**Comment by gssbzn** [comment]
This was done by #141 and released on [v0.5.0](https://github.com/mongodb/mongocli/releases/tag/v0.5.0)
