### ISSUE TITLE
List available projects by name instead of asking for an ID

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mongocli#200]
I am following getting started instructions [here](https://docs.mongodb.com/mongocli/master/quick-start/#set-the-id-of-the-project-in-your-profile). The third step is:

> Set the ID of the project in your profile.

> When the command prompts you, enter your project ID.

I do not get this prompt - I am only prompted for public and private API keys.

I tried with and without `~/.config/mongocli.toml               ` existing, same behavior.

**Comment by gssbzn** [comment]
Hi @p-mongo what version of mongocli are you using (`mongocli --version`), this was added to [v0.5.0](https://github.com/mongodb/mongocli/releases/tag/v0.5.0)

**Comment by p-mongo** [comment]
I was using 0.2.0 it seems because `make install` did not install the binary in a usable location.

Master does prompt for project id, but what am I supposed to enter there? A list of existing projects would perhaps be helpful.

**Comment by gssbzn** [comment]
a list of existing projects has always been on my wish list since the first alpha but has always been left on the cutting floor, we'll see if we can address this for our next set of milestones

**Comment by gssbzn** [comment]
Edited title to match what we want to implement as original issue is a non issue
