### ISSUE TITLE
Usage text is not shown when usage is incorrect

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mongocli#202]
Now on master, I get:

<pre>
carbon% mongocli iam project  create     
Error: accepts 1 arg(s), received 0
</pre>

Since the usage was not correct, I would like mongocli to tell me what the correct usage is.

**Comment by gssbzn** [comment]
this relates to #198, sadly our current [CLI framework](https://github.com/spf13/cobra) is either always or never on usage, we do plan to do some significant improvements on usability next and we are already talking about improving some of our error messages

**Comment by p-mongo** [comment]
What would also be helpful is for (at least common) command line options to be accepted/ignored such that the following usage is possible:

<pre>
# works
mongocli atlas  --projectId X clusters list

# fails
mongocli atlas  --projectId X 

# still fails
mongocli atlas  --projectId X  help
</pre>

If I am working within a project, I would like to setup e.g. an alias like this:

<pre>
alias m='mongocli atlas  --projectId X'
</pre>

... and then be able to explore and receive help for commands without having to retype project id argument.

**Comment by gssbzn** [comment]
@p-mongo for that project id usage you can do `mongocli config set projecy_id (ID) ` and it should be set at the profile level so you don't have to do `- - project` again, and if you do `- - project ` with a different ID from the profile it should take precedence

**Comment by gssbzn** [comment]
Circling back on usage, we are waiting on https://github.com/spf13/cobra/pull/842 to be merge and release so we can take advantage of it in our own case

**Comment by gssbzn** [comment]
@p-mongo we have made an internal change as cobra is taking their time to address this, if you can test the latest master and let us know what you think we'd really appreciate it.

If not we're planning a release this week that should include this along with other improvements
