### ISSUE TITLE
Listing organizations does not work

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mongocli#207]
On master:

<pre>
carbon% mongocli --version   
mongocli version v1.0.0-rc3-5-g335e040

carbon% mongocli iam org list
Error: unsupported service: cloud
</pre>

I can list by curling the API: https://cloud.mongodb.com/api/atlas/v1.0/orgs

**Comment by gssbzn** [comment]
I've answered this on mongodb/go-client-mongodb-atlas#100 depending on the outcome there we can see mongcoli implementing this for Atlas but right now Organizations is an Ops Manager feature only

**Comment by gssbzn** [comment]
closed via e9b2e2b338b5577cfbe7231a08a7bd96ef3e2fb1
