### ISSUE TITLE
Re: Unable to access Ops Manager using API 

### ISSUE THREAD

**Issue by gauravtaneja1984** [mongodb/mongocli#261]
Hello,

I am trying to connect ops manager using public API for the first time and getting below error. Please help me to fix this issue.

 curl --user '{XXX}:{XXX}' --digest --header 'Accept: application/json' --include  --request GET "<xxx>:<xx>/api/public/v1.0/groups?pretty=true"

Content-Type: application/json
Content-Length: 106

{
  "reason" : "Unauthorized",
  "error" : 401,
  "detail" : "You are not authorized for this resource."
}

Thanks!!

**Comment by gssbzn** [comment]
Hi @gauravtaneja1984 seems like you're trying to use `curl` to access the API. This project is a CLI and as such we reserve it to address issues related with the cli. If you have a problem with the CLI please let us know what version are you using, the command you're running what error are you getting and what is the expected result.

For any issue related to Ops Manager please contact [MongoDB support](https://support.mongodb.com/welcome) directly.

**Comment by gssbzn** [comment]
@gauravtaneja1984 to list your projects with the cli you can do `mongocli iam projects ls` just remember to provide the correct API keys and the Ops Manager base URL, you can do this with `mongocli config --service ops-manager`

**Comment by gauravtaneja1984** [comment]
Thanks!!
