### ISSUE TITLE
Clobber log output file by default

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mongocli#461]
The standard Unix utility behavior is to clobber files specified as write output.

When mongocli downloads logs, it refuses to run if the destination file exists:

```
./bin/mongocli atlas logs download atlas-51fpbe-shard-00-01.zjgzi.mongodb.net mongodb.gz --projectId 5f49cd4b6d8c874ca774824f --out -
Error: open -: file exists
```

As a user of a unix-like operating system, I expected mongocli to clobber the output file, especially one that it created by itself without direction from me (#460, I expected default destination to be standard output).

If no-clobber behavior is desired, it should be provided as an option, and in that case mongocli should ask the user whether to clobber the file if the input device is a terminal and not immediately give up. See, for example, `cp -i` behavior:

```
serene% cp -i bin/mongocli - 
cp: overwrite '-'? 
```

**Comment by gssbzn** [comment]
My personal opinion on clobbering by default is that it's risky and a usability issue, with that said we are willing to add the inverse of `cp -i` and it's to instruct the download to clobber with an extra flag, adding this will also enable you to do something like
`mongocli atlas logs download atlas-51fpbe-shard-00-01.zjgzi.mongodb.net mongodb.gz --out /dev/stdout` which should address #460

**Comment by p-mongo** [comment]
I understand how someone not familiar with unix command line may be surprised by output files being clobbered but this is the behavior of the vast majority of unix programs. Log files are generally unconditionally appended to by default.

> and a usability issue

In my opinion the usability issue is that mongocli refuses to work unless the user deletes files that mongocli created.

**Comment by gssbzn** [comment]
Like I mentioned in this case will add the ability to over write the destination file but it won't be default, also for clarification and also why this command works the way it does is that you won't be able to get a plain text file, it'll be a gzip file you'll need to unzip, this is currently and atlas limitation

**Comment by p-mongo** [comment]
I am aware that the atlas api provides gzipped logs but this doesn't mean a commond-line tool must only provide gzipped logs.
