### ISSUE TITLE
Problems installing mongocli with homebrew 

### ISSUE THREAD

**Issue by gregory-akins** [mongodb/mongocli#592]
Installing from brew as the MongoDb docs suggest https://docs.mongodb.com/mongocli/stable/install

Thinking this might be a function of 1.11 being such a "fresh" release?  But maybe a path is wrong in the brew recipe.

**$ brew tap mongodb/brew**
brew install mongocli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
htmltest                                       mpdecimal                                      vitess
==> Updated Formulae
Updated 130 formulae.
==> New Casks
digital                                        duckstation                                    sengi
==> Updated Casks
Updated 208 casks.

==> Tapping mongodb/brew
Cloning into '/usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 513 (delta 1), reused 2 (delta 0), pack-reused 503
Receiving objects: 100% (513/513), 109.93 KiB | 1.55 MiB/s, done.
Resolving deltas: 100% (239/239), done.
Tapped 11 formulae (40 files, 185.7KB).

**$ brew install mongocli**
==> Installing mongocli from mongodb/brew
==> Downloading https://github.com/mongodb/mongocli/releases/download/v1.11.0/mongocli_1.11.0_macos_x86_64.zip
#=#=#                                                                         
### **curl: (22) The requested URL returned error: 404** 
Error: Failed to download resource "mongocli"
Download failed: https://github.com/mongodb/mongocli/releases/download/v1.11.0/mongocli_1.11.0_macos_x86_64.zip

**Comment by gregory-akins** [comment]
Closing this and reopening in mongodb homebrew project

**Comment by andreaangiolillo** [comment]
Hi @gregory-akins,

You got that error because 1.11.0 wasn’t yet published when you have run brew.
Let me know if you keep getting the same error.

Thanks,

**Comment by gregory-akins** [comment]
I thought that might be the case.  Just tried again, and it installed successfully.

Thanks
