### ISSUE TITLE
Cannot add atlas user to existing team from mongocli

### ISSUE THREAD

**Issue by mapoulos** [mongodb/mongocli#606]
**Describe the bug**
I cannot add a user to a team using the mongocli. 

**To Reproduce**
```
mongocli iam teams users add \
   --teamId <TEAM_ID> \
   --orgId <ORG_ID> \
    my.user@washpost.com
```

**Expected behavior**
The user is added

**Screenshots**
```
Error: POST https://cloud.mongodb.com/api/atlas/v1.0/orgs/<ORG_ID>/teams/<TEAM_ID>/users: 400 (request "Bad Request") Received JSON for the null attribute does not match expected format.
```

**Desktop (please complete the following information):**
 - OS: OS X 10.15.7 (Catalina)

```
 $ mongocli --version
mongocli version: 1.10.0
git version: 76b17fc49f4662110b12aa0a60984b05a6e0d28e
Go version: go1.15
   os: darwin
   arch: amd64
   compiler: gc
```

**Additional context**
I can create a team and pass in a list of users. But I cannot update an existing team.

**Comment by gssbzn** [comment]
Hi @mapoulos, it seems like you are trying to use an email as a parameter,[ mongocli iam teams users add](https://docs.mongodb.com/mongocli/stable/reference/iam/iam-team-user-add) needs the user ID, you can get it by [describing](https://docs.mongodb.com/mongocli/stable/reference/iam/iam-user-describe) the user by email

Can you please confirm if this error still shows when using a valid user ID?

**Comment by mapoulos** [comment]
That did the trick. The discrepancy still exists between `team` creation (where the e-mail is valid) and `team` update (where the ID is needed and username won't work) is still not desirable, but I understand that would be a feature request. 

Thanks for helping me resolve the issue!

**Comment by gssbzn** [comment]
I'm glad it solved the issue. Please feel free to submit a request [here](https://feedback.mongodb.com/forums/930808-mongodb-cli) and we can look into improving this for sure
