### ISSUE TITLE
Missing required argument in agents list documentation

### ISSUE THREAD

**Issue by hyww** [mongodb/mongocli#741]
**Describe the bug**
`mongocli cloud-manager agents list` shows the following message, but [documentation](https://docs.mongodb.com/mongocli/stable/command/mongocli-cloud-manager-agents-list/) (or the command with `--help`) says nothing about the required argument.

```bash
$ mongocli cloud-manager agents list
Error: "mongocli cloud-manager agents list" requires 1 argument

Usage:  mongocli cloud-manager agents list [flags]
```

**To Reproduce**
1. Run `mongocli cloud-manager agents list`
2. See error

**Expected behavior**
Please explain what you expected to happen.

Tell users the required argument should be  one of `{"AUTOMATION", "MONITORING", "BACKUP"}` according to [here](https://github.com/mongodb/mongocli/blob/master/internal/cli/opsmanager/agents/list.go#L61).

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS:  Ubuntu Linux 18.04 (WSL1 on Windows 10 Professional 2004 19041.746)
 - MongoCLI version 1.17.1

**Additional context**

**Comment by gssbzn** [comment]
Thanks for the report, this should be fixed now
