### ISSUE TITLE
cloud-manager agents version list is not supported

### ISSUE THREAD

**Issue by hyww** [mongodb/mongocli#742]
**Describe the bug**
`mongocli cloud-manager agents version list` says `Error: unsupported service: cloud-manager`

**To Reproduce**
1. Run `mongocli cloud-manager agents version list`
2. See error

**Expected behavior**
Please explain what you expected to happen.

List of agents and their version displayed.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS:  Ubuntu Linux 18.04 (WSL1 on Windows 10 Professional 2004 19041.746)
 - MongoCLI version 1.17.1

**Additional context**

**Comment by gssbzn** [comment]
Sorry, this feature was intentionally ops manager only but let me see if we can safely enable it for cloud manager

**Comment by andreaangiolillo** [comment]
Hello @hyww,
I have created an internal ticket to fix this issue [CLOUDP-94706:cloud-manager agents version list is not supported](https://jira.mongodb.org/browse/CLOUDP-94706). I will open a PR to fix it.

Thanks,
Andrea

**Comment by andreaangiolillo** [comment]
PR: https://github.com/mongodb/mongocli/pull/756
