### ISSUE TITLE
Unable to create dbusers: Put error EOF

### ISSUE THREAD

**Issue by yebo29** [mongodb/mongocli#941]
When attempting to create a dbuser I get the below error:
`Error: Put "https://<ops-manager-url>/api/public/v1.0/groups/5a1f36b65168b41d6e9f0813/automationConfig": EOF`
The commands I have attempted:
```
mongocli ops-manager dbusers create --username test_user --password "<password>" --authDB TaxHub --role read@TaxHub --projectId 5a1f36b65168b41d6e9f0813

mongocli ops-manager dbusers create --username test_user --password "<password>" --authDB TaxHubMT --role read@TaxHubMT,read@TaxHub --projectId 5a1f36b65168b41d6e9f0813

mongocli ops-manager dbusers create --username test_user
```
All end up with the same error. Is there something I'm missing or doing wrong? Running mongocli version 1.21.0 installed via homebrew on macOS Big Sur on a MacBook Pro Intel. mongocli is attempting to talk to Ops Manager version `4.0.15.50565.20190823T1920Z`. Adding the user via the ops manager webui with the same parameters works fine. 

My mongocli.toml:
```
mongosh_path = "/usr/local/bin/mongosh"

[default]
  ops_manager_url = "https://<url>/"
  organization_id = "default-org-id (there's only one)"
  public_api_key = "my username <me@domain.com>"
  project_id = "default-project-id"
  private_api_key = "my public api key created via the account section in the web ui"
  service = "ops-manager"
blahblah ~ $ which mongosh
/usr/local/bin/mongosh
```
Running list and get operations works fine without any errors (such as `mongocli ops-manager dbusers list` or `mongocli iam project list`). I don't know how to create a private api key and documentation is pretty much non-existent for version 4.0 of ops manager. We are upgrading to version 4.4 soon and I wonder if that may fix my issue.

Thanks for your help.

**Comment by andreaangiolillo** [comment]
Hi @yebo29,
Ops Manager 4.0 is not supported with MongoCLI, please have a look at this doc page ([Compatibility](https://docs.mongodb.com/mongocli/stable/install/compatibility/#atlas--cloud-manager--and-ops-manager-versions)) for more information. 
I believe the issue that you are having with the creation of a dbuser should disappear with v.4.4. Please, let us know if you keep having the same issue with v4,4.
From what I remember of Ops Manager 4.0, your `mongocli.tolm` looks correct. Once you've upgraded to v4.4 you will be able to create your programmatic API keys (public + private keys) by following [Programmatic Access to Ops Manager](https://docs.opsmanager.mongodb.com/current/tutorial/manage-programmatic-api-keys/).

**Comment by gssbzn** [comment]
@yebo29 feel free to reopen this issue if the error still persist on Ops Manager 4.4, please note like mentioned by @andreaangiolillo MongoCLI has never supported Ops Manager 4.0 but also Ops Manager 4.0 and 4.2 have reached EOL and 4.4 planned EOL is July this year at which point will stop supporting it via the CLI as well.
